import { Language } from './types';

export const SUPPORTED_LANGUAGES: Language[] = [
  { value: 'Arabic', label: 'العربية (Arabic)' },
  { value: 'Assamese', label: 'অসমীয়া (Assamese)' },
  { value: 'Bengali', label: 'বাংলা (Bengali)' },
  { value: 'Bodo', label: 'बोडो (Bodo)' },
  { value: 'Dogri', label: 'डोगरी (Dogri)' },
  { value: 'English', label: 'English' },
  { value: 'French', label: 'Français (French)' },
  { value: 'German', label: 'Deutsch (German)' },
  { value: 'Gujarati', label: 'ગુજરાતી (Gujarati)' },
  { value: 'Hindi', label: 'हिन्दी (Hindi)' },
  { value: 'Japanese', label: '日本語 (Japanese)' },
  { value: 'Kannada', label: 'ಕನ್ನಡ (Kannada)' },
  { value: 'Kashmiri', label: 'कश्मीरी (Kashmiri)' },
  { value: 'Konkani', label: 'कोंकणी (Konkani)' },
  { value: 'Korean', label: '한국어 (Korean)' },
  { value: 'Maithili', label: 'मैथिली (Maithili)' },
  { value: 'Malayalam', label: 'മലയാളം (Malayalam)' },
  { value: 'Mandarin Chinese', label: '中文 (Mandarin)' },
  { value: 'Manipuri', label: 'মেইতেই (Manipuri)' },
  { value: 'Marathi', label: 'मराठी (Marathi)' },
  { value: 'Nepali', label: 'नेपाली (Nepali)' },
  { value: 'Odia', label: 'ଓଡ଼ିଆ (Odia)' },
  { value: 'Portuguese', label: 'Português (Portuguese)' },
  { value: 'Punjabi', label: 'ਪੰਜਾਬੀ (Punjabi)' },
  { value: 'Russian', label: 'Русский (Russian)' },
  { value: 'Sanskrit', label: 'संस्कृतम् (Sanskrit)' },
  { value: 'Santali', label: 'ᱥᱟᱱᱛᱟᱲᱤ (Santali)' },
  { value: 'Sindhi', label: 'सिन्धी (Sindhi)' },
  { value: 'Spanish', label: 'Español (Spanish)' },
  { value: 'Tamil', label: 'தமிழ் (Tamil)' },
  { value: 'Telugu', label: 'తెలుగు (Telugu)' },
  { value: 'Urdu', label: 'اردو (Urdu)' },
  { value: 'Vietnamese', label: 'Tiếng Việt (Vietnamese)' },
];