

import React from 'react';

type RichTextFunction = (...args: React.ReactNode[]) => React.ReactNode;

export interface StringCollection {
  [key: string]: string | RichTextFunction;
}

interface LocalizedStrings {
  [languageCode: string]: StringCollection;
}

export const strings: LocalizedStrings = {
  en: {
    appTitle: 'Multilingual Government Form Translator',
    appSubtitle: 'Upload an image or PDF of a government form, select a language, and our AI will provide a structured translation and a simplified explanation.',
    resultCardTitle: 'Simplified Explanation',
    placeholderTitle: 'Results will appear here',
    placeholderSubtitle: 'Once you upload a form and translate it, the structured translation and a simplified explanation will be displayed in this area.',
    errorTitle: 'Error',
    formStep1: 'Provide Form Content',
    formStep2: 'Select Language',
    tabUploadFile: 'Upload File',
    tabFormLibrary: 'Form Library',
    tabPasteText: 'Paste Text',
    uploadCTA1: 'Upload a file',
    uploadCTA2: 'or drag and drop',
    uploadHint: 'PNG, JPG, PDF',
    changeFile: 'Change file',
    librarySearchPlaceholder: 'Search for a form...',
    filterByCategory: 'Filter by category',
    filterByState: 'Filter by state',
    allCategories: 'All Categories',
    allStates: 'All States',
    noFormsFound: 'No forms found matching your criteria.',
    textAreaPlaceholder: 'Paste the text content of the form here...',
    languageSearchPlaceholder: 'Search language...',
    submitButton: 'Translate & Simplify',
    submitButtonLoading: 'Processing...',
    loaderTitle: 'Analyzing Document...',
    loaderSubtitle: 'This may take a moment. Please wait.',
    copied: 'Copied!',
    formPreviewTitle: 'Form Preview',
    formPreviewPlaceholder: 'Select a form from the list to see its content.',
  },
  es: {
    appTitle: 'Traductor Multilingüe de Formularios Gubernamentales',
    appSubtitle: 'Sube una imagen o PDF de un formulario gubernamental, selecciona un idioma y nuestra IA proporcionará una traducción estructurada y una explicación simplificada.',
    resultCardTitle: 'Explicación Simplificada',
    placeholderTitle: 'Los resultados aparecerán aquí',
    placeholderSubtitle: 'Una vez que subas y traduzcas un formulario, la traducción estructurada y una explicación simplificada se mostrarán en esta área.',
    errorTitle: 'Error',
    formStep1: 'Proporciona el Contenido del Formulario',
    formStep2: 'Selecciona el Idioma',
    tabUploadFile: 'Subir Archivo',
    tabFormLibrary: 'Biblioteca de Formularios',
    tabPasteText: 'Pegar Texto',
    uploadCTA1: 'Sube un archivo',
    uploadCTA2: 'o arrastra y suelta',
    uploadHint: 'PNG, JPG, PDF',
    changeFile: 'Cambiar archivo',
    librarySearchPlaceholder: 'Buscar un formulario...',
    filterByCategory: 'Filtrar por categoría',
    filterByState: 'Filtrar por estado',
    allCategories: 'Todas las Categorías',
    allStates: 'Todos los Estados',
    noFormsFound: 'No se encontraron formularios que coincidan con sus criterios.',
    textAreaPlaceholder: 'Pega el contenido de texto del formulario aquí...',
    languageSearchPlaceholder: 'Buscar idioma...',
    submitButton: 'Traducir y Simplificar',
    submitButtonLoading: 'Procesando...',
    loaderTitle: 'Analizando Documento...',
    loaderSubtitle: 'Esto puede tardar un momento. Por favor espera.',
    copied: '¡Copiado!',
    formPreviewTitle: 'Vista Previa del Formulario',
    formPreviewPlaceholder: 'Selecciona un formulario de la lista para ver su contenido.',
  },
  ar: {
    appTitle: 'مترجم النماذج الحكومية متعدد اللغات',
    appSubtitle: 'قم بتحميل صورة أو ملف PDF لنموذج حكومي، اختر لغة، وسيقدم ذكاؤنا الاصطناعي ترجمة منظمة وشرحًا مبسطًا.',
    resultCardTitle: 'شرح مبسط',
    placeholderTitle: 'ستظهر النتائج هنا',
    placeholderSubtitle: 'بمجرد تحميل نموذج وترجمته، ستُعرض الترجمة المنظمة والشرح المبسط في هذه المنطقة.',
    errorTitle: 'خطأ',
    formStep1: 'توفير محتوى النموذج',
    formStep2: 'اختر اللغة',
    tabUploadFile: 'تحميل ملف',
    tabFormLibrary: 'مكتبة النماذج',
    tabPasteText: 'لصق النص',
    uploadCTA1: 'قم بتحميل ملف',
    uploadCTA2: 'أو اسحبه وأفلته',
    uploadHint: 'PNG, JPG, PDF',
    changeFile: 'تغيير الملف',
    librarySearchPlaceholder: 'ابحث عن نموذج ...',
    filterByCategory: 'التصفية حسب الفئة',
    filterByState: 'التصفية حسب الولاية',
    allCategories: 'جميع الفئات',
    allStates: 'جميع الولايات',
    noFormsFound: 'لم يتم العثور على نماذج تطابق معاييرك.',
    textAreaPlaceholder: 'الصق المحتوى النصي للنموذج هنا...',
    languageSearchPlaceholder: 'ابحث عن لغة...',
    submitButton: 'ترجمة وتبسيط',
    submitButtonLoading: 'قيد المعالجة...',
    loaderTitle: 'جاري تحليل المستند...',
    loaderSubtitle: 'قد يستغرق هذا بعض الوقت. يرجى الانتظار.',
    copied: 'تم النسخ!',
    formPreviewTitle: 'معاينة النموذج',
    formPreviewPlaceholder: 'اختر نموذجًا من القائمة لرؤية محتواه.',
  },
  fr: {
    appTitle: 'Traducteur de formulaires gouvernementaux multilingues',
    appSubtitle: 'Téléchargez une image ou un PDF d\'un formulaire gouvernemental, sélectionnez une langue, et notre IA fournira une traduction structurée et une explication simplifiée.',
    resultCardTitle: 'Explication simplifiée',
    placeholderTitle: 'Les résultats apparaîtront ici',
    placeholderSubtitle: 'Une fois que vous aurez téléchargé et traduit un formulaire, la traduction structurée et une explication simplifiée s\'afficheront dans cette zone.',
    errorTitle: 'Erreur',
    formStep1: 'Fournir le contenu du formulaire',
    formStep2: 'Sélectionner la langue',
    tabUploadFile: 'Télécharger un fichier',
    tabFormLibrary: 'Bibliothèque de formulaires',
    tabPasteText: 'Coller le texte',
    uploadCTA1: 'Télécharger un fichier',
    uploadCTA2: 'ou glisser-déposer',
    uploadHint: 'PNG, JPG, PDF',
    changeFile: 'Changer de fichier',
    librarySearchPlaceholder: 'Rechercher un formulaire...',
    filterByCategory: 'Filtrer par catégorie',
    filterByState: 'Filtrer par état',
    allCategories: 'Toutes les catégories',
    allStates: 'Tous les états',
    noFormsFound: 'Aucun formulaire ne correspond à vos critères.',
    textAreaPlaceholder: 'Collez le contenu textuel du formulaire ici...',
    languageSearchPlaceholder: 'Rechercher une langue...',
    submitButton: 'Traduire et simplifier',
    submitButtonLoading: 'Traitement en cours...',
    loaderTitle: 'Analyse du document...',
    loaderSubtitle: 'Cela peut prendre un moment. Veuillez patienter.',
    copied: 'Copié !',
    formPreviewTitle: 'Aperçu du formulaire',
    formPreviewPlaceholder: 'Sélectionnez un formulaire dans la liste pour voir son contenu.',
  },
  hi: {
    appTitle: 'बहुभाषी सरकारी फॉर्म अनुवादक',
    appSubtitle: 'एक सरकारी फॉर्म की एक छवि या पीडीएफ अपलोड करें, एक भाषा चुनें, और हमारा AI एक संरचित अनुवाद और एक सरलीकृत स्पष्टीकरण प्रदान करेगा।',
    resultCardTitle: 'सरलीकृत स्पष्टीकरण',
    placeholderTitle: 'परिणाम यहां दिखाई देंगे',
    placeholderSubtitle: 'एक बार जब आप एक फॉर्म अपलोड और अनुवाद कर लेंगे, तो संरचित अनुवाद और एक सरलीकृत स्पष्टीकरण इस क्षेत्र में प्रदर्शित किया जाएगा।',
    errorTitle: 'त्रुटि',
    formStep1: 'फॉर्म सामग्री प्रदान करें',
    formStep2: 'भाषा चुनें',
    tabUploadFile: 'फ़ाइल अपलोड करें',
    tabFormLibrary: 'फॉर्म लाइब्रेरी',
    tabPasteText: 'टेक्स्ट पेस्ट करें',
    uploadCTA1: 'एक फ़ाइल अपलोड करें',
    uploadCTA2: 'या खींचें और छोड़ें',
    uploadHint: 'PNG, JPG, PDF',
    changeFile: 'फ़ाइल बदलें',
    librarySearchPlaceholder: 'एक फॉर्म खोजें...',
    filterByCategory: 'श्रेणी के अनुसार फ़िल्टर करें',
    filterByState: 'राज्य द्वारा फ़िल्टर करें',
    allCategories: 'सभी श्रेणियाँ',
    allStates: 'सभी राज्य',
    noFormsFound: 'आपके मानदंडों से मेल खाने वाला कोई फॉर्म नहीं मिला।',
    textAreaPlaceholder: 'फॉर्म की पाठ्य सामग्री यहाँ पेस्ट करें...',
    languageSearchPlaceholder: 'भाषा खोजें...',
    submitButton: 'अनुवाद और सरल करें',
    submitButtonLoading: 'संसाधित हो रहा है...',
    loaderTitle: 'दस्तावेज़ का विश्लेषण किया जा रहा है...',
    loaderSubtitle: 'इसमें थोड़ा समय लग सकता है। कृपया प्रतीक्षा करें।',
    copied: 'कॉपी किया गया!',
    formPreviewTitle: 'फ़ॉर्म पूर्वावलोकन',
    formPreviewPlaceholder: 'इसकी सामग्री देखने के लिए सूची से एक फ़ॉर्म चुनें।',
  },
  ja: {
    appTitle: '多言語対応 政府フォーム翻訳ツール',
    appSubtitle: '政府フォームの画像またはPDFをアップロードし、言語を選択すると、AIが構造化された翻訳と簡単な説明を提供します。',
    resultCardTitle: '簡単な説明',
    placeholderTitle: '結果はここに表示されます',
    placeholderSubtitle: 'フォームをアップロードして翻訳すると、構造化された翻訳と簡単な説明がこのエリアに表示されます。',
    errorTitle: 'エラー',
    formStep1: 'フォームのコンテンツを提供',
    formStep2: '言語を選択',
    tabUploadFile: 'ファイルをアップロード',
    tabFormLibrary: 'フォームライブラリ',
    tabPasteText: 'テキストを貼り付け',
    uploadCTA1: 'ファイルをアップロード',
    uploadCTA2: 'またはドラッグ＆ドロップ',
    uploadHint: 'PNG, JPG, PDF',
    changeFile: 'ファイルを変更',
    librarySearchPlaceholder: 'フォームを検索...',
    filterByCategory: 'カテゴリで絞り込む',
    filterByState: '州で絞り込む',
    allCategories: 'すべてのカテゴリ',
    allStates: 'すべての州',
    noFormsFound: '条件に合うフォームが見つかりませんでした。',
    textAreaPlaceholder: 'フォームのテキスト内容をここに貼り付けてください...',
    languageSearchPlaceholder: '言語を検索...',
    submitButton: '翻訳して簡略化',
    submitButtonLoading: '処理中...',
    loaderTitle: 'ドキュメントを分析中...',
    loaderSubtitle: '少々お待ちください。',
    copied: 'コピーしました！',
    formPreviewTitle: 'フォームのプレビュー',
    formPreviewPlaceholder: 'リストからフォームを選択して内容を表示します。',
  },
};